name: Main CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-core:
    uses: ./.github/workflows/ci-core.yml
    with:
      java-version: '17'

  code-quality:
    needs: ci-core
    uses: ./.github/workflows/code-quality.yml
    with:
      artifact-path: ${{ needs.ci-core.outputs.artifact-path }}

  integration-tests:
    needs: ci-core
    uses: ./.github/workflows/integration-tests.yml
    with:
      java-version: '17'
      artifact-path: ${{ needs.ci-core.outputs.artifact-path }}
